### ISSUE TITLE
Verify MDM.cer file fails in Windows

### ISSUE THREAD

**Issue by TomSelleck** [grinich/mdmvendorsign#4]
Problem code is:

    p('Verifying %s ... ' % cli_args['mdm'])
    mdm_cert_file = open(cli_args['mdm']).read()
    args = ['openssl', 'x509', '-noout', '-inform', 'DER' ]
    command = subprocess.Popen(args, stdout=subprocess.PIPE, stdin=subprocess.PIPE, stderr=subprocess.STDOUT)
    output, error = command.communicate(input = mdm_cert_file)	

Error is as follows:

    'unable to load certificate\r\n8240:error:0D06B08E:asn1 encoding   routines:ASN1_D2I_READ_BIO:not enough data:.\\crypto\\asn1\\a_d2i_fp.c:234:\r\n'

Simple and quick solution is to read file as binary as follows:

    with open(cli_args['mdm'], 'rb') as f:
            mdm_cert_file = f.read()
            args = ['openssl', 'x509', '-noout', '-inform', 'DER' ]
            command = subprocess.Popen(args, stdout=subprocess.PIPE, stdin=subprocess.PIPE, stderr=subprocess.STDOUT)
            output, error = command.communicate(input = mdm_cert_file)	
             ....

**Comment by grinich** [comment]
should be fixed in https://github.com/grinich/mdmvendorsign/pull/5 :smile:
